//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Linq;

using OpenDoPEModel;
// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opendope.org/answers")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://opendope.org/answers", IsNullable=false)]
public partial class answers {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("answer", typeof(answer))]
    [System.Xml.Serialization.XmlElementAttribute("repeat", typeof(repeat))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opendope.org/answers")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://opendope.org/answers", IsNullable=false)]
public partial class answer {

    public override bool Equals(object obj)
    {
        answer other = obj as answer;

        return ((other.qref.Equals(this.qref)));
    }

    public override int GetHashCode()
    {
        // GetHashCode should be a lot quicker than Equals, but doesn't need to be unique.
        // See http://stackoverflow.com/questions/16340/how-do-i-generate-a-hashcode-from-a-byte-array-in-c-sharp
        return qref.GetHashCode();
    }

    
    private string qrefField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string qref {
        get {
            return this.qrefField;
        }
        set {
            this.qrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opendope.org/answers")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://opendope.org/answers", IsNullable=false)]
public partial class repeat {

    public override bool Equals(object obj)
    {
        repeat other = obj as repeat;

        if (this.row.Length != other.row.Length) return false;

        return ListEquality.ScrambledEquals<repeatRow>(row.OfType<repeatRow>().ToList<repeatRow>(), 
            other.row.OfType<repeatRow>().ToList<repeatRow>());
    }

    public override int GetHashCode()
    {
        // GetHashCode should be a lot quicker than Equals, but doesn't need to be unique.
        // See http://stackoverflow.com/questions/16340/how-do-i-generate-a-hashcode-from-a-byte-array-in-c-sharp
        return qref.GetHashCode();
    }


    private repeatRow[] rowField;
    
    private string qrefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("row")]
    public repeatRow[] row {
        get {
            return this.rowField;
        }
        set {
            this.rowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string qref {
        get {
            return this.qrefField;
        }
        set {
            this.qrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://opendope.org/answers")]
public partial class repeatRow {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("answer", typeof(answer))]
    [System.Xml.Serialization.XmlElementAttribute("repeat", typeof(repeat))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
